where_single_line = true
format_strings = true
hard_tabs = true
match_block_trailing_comma = true
max_width = 80
reorder_impl_items = true
use_try_shorthand = true
wrap_comments = true
blank_lines_upper_bound = 1
normalize_comments = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
use_field_init_shorthand = true
