[package]
name = "zauth"
version = "0.1.0"
edition = "2018"
authors = ["Rien Maertens <rien.maertens@posteo.be>"]

[dependencies]
askama = { version = "0.9.0", features = ["with-rocket", "mime", "mime_guess"] }
error-chain = "0.12"
base64 = "0.10"
bincode = "1.0"
pwhash = "0.3"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.1"
urlencoding = "1.0"
rand = "0.5"
regex = "1.0"
rocket = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4"
tempfile = "3.1"
maplit = "1.0"
parking_lot = { version = "0.10", features = ["nightly"] }

[dependencies.rocket_contrib]
version="0.4.2"
default-features = false
features = ["json", "diesel_postgres_pool",  "serve"]

