[package]
name = "zauth"
version = "0.1.0"
authors = ["Rien Maertens <maertensrien@gmail.com>"]

[dependencies]
base64 = "0.9"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.1"
regex = "1.0"
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5"

[dependencies.rocket_contrib]
version = "0.3"
default-features = false
features = ["handlebars_templates"]
