[package]
name = "zauth"
version = "0.1.0"
edition = "2018"
authors = ["Rien Maertens <rien.maertens@posteo.be>"]

[dependencies]
askama = { version = "0.9.0", features = ["with-rocket", "mime", "mime_guess"] }
base64 = "0.12"
bincode = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono"] }
diesel-derive-enum = { version = "1", features = ["postgres"] }
diesel_migrations = "1.4"
lazy_static = "1.1"
maplit = "1.0"
parking_lot = { version = "0.11", features = ["nightly"] }
pwhash = "0.3"
rand = "0.7"
regex = "1.0"
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json", "diesel_postgres_pool",  "serve"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.6"
tempfile = "3.1"
thiserror = "1.0.20"
urlencoding = "1.0"
zauth_derive = { version = "0.1", path = "./zauth_derive/" }
zauth_record = { version = "0.1", path = "./zauth_record/" }

