[package]
name = "zauth"
version = "0.1.0"
authors = ["Rien Maertens <maertensrien@gmail.com>"]

[dependencies]
base64 = "0.10"
bincode = "1.0"
bcrypt = "0.6"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.1"
urlencoding = "1.0"
rand = "0.5"
regex = "1.0"
rocket = "0.4.2"
rocket_http_authentication = { version = "0.1", path = "./http_authentication/" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4"
tempfile = "3.1"

[dependencies.rocket_contrib]
version="0.4.2"
default-features = false
features = ["handlebars_templates", "json", "diesel_sqlite_pool"]

