[package]
name = "zauth"
version = "0.1.0"
edition = "2018"
authors = ["Rien Maertens <rien.maertens@posteo.be>"]

[dependencies]
askama = { version = "0.10", features = ["with-rocket", "mime", "mime_guess"] }
askama_rocket = "0.10"
base64 = "0.12"
bincode = "1.0"
pwhash = "0.3"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.1"
lettre = { version = "0.10.0-rc.3", features = ["builder", "smtp-transport"] }
urlencoding = "1.0"
toml = "0.4"
rand = "0.7"
regex = "1.0"
rocket = "0.4.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.7"
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono"] }
diesel-derive-enum = { version = "1", features = ["postgres"] }
diesel_migrations = "1.4"
tempfile = "3.1"
maplit = "1.0"
parking_lot = { version = "0.11", features = ["nightly"] }
thiserror = "1.0.20"
threads_pool = "0.2.6"
validator = "0.11"
validator_derive = "0.11"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "diesel_postgres_pool",  "serve"]
