version: '3.5'
services:
  zauth:
    image: ghcr.io/ZeusWPI/zauth:latest
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - database
    command: >
      sh -c "./docker_misc/wait_for_service database 5432 && diesel --database-url 'postgresql://zauth:zauth@database/zauth' database setup && ROCKET_ENV=production zauth"

  database:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: zauth
      POSTGRES_PASSWORD: zauth
    volumes:
      - zauth-database:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 127.0.0.1:8080:8080

volumes:
  zauth-database:
