version: '3.5'
services:
  zauth:
    image: ghcr.io/zeuswpi/zauth:latest
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - database
    command: >
      sh -c "diesel --database-url 'postgresql://zauth:zauth@database/zauth' database setup && RUST_LOG=info ROCKET_PROFILE=release zauth"
    volumes:
      - ${PWD}/Rocket.toml:/usr/src/zauth/Rocket.toml
  
  smtp-relay:
    image: dcagatay/emailrelay
    command: --forward-on-disconnect --forward-to smtp.ugent.be:25
    volumes:
      - zauth-mailrelay:/var/spool/emailrelay

  database:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: zauth
      POSTGRES_PASSWORD: zauth
    volumes:
      - zauth-database:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: "pg_isready -U zauth"
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 127.0.0.1:8080:8080

volumes:
  zauth-database:
