[default]
user_session_seconds = 604800              # 1 week
client_session_seconds = 300               # 5 minutes
authorization_token_seconds = 300          # 5 minutes
email_confirmation_token_seconds = 604800  # 1 week
admin_email = "admin@localhost"
secure_token_length = 64
bcrypt_cost = 12
base_url = "http://localhost:8000"
mail_queue_size = 32
mail_queue_wait_seconds = 1
mail_from = "zauth@localhost"
mail_server = "stub"
mailing_list_name = "Leden"
mailing_list_email = "leden@zeus.ugent.be"
maximum_pending_users = 25

[debug]
secret_key = "1vwCFFPSdQya895gNiO556SzmfShG6MokstgttLvwjw="
ec_private_key = "keys/replace_me.pem"
bcrypt_cost = 4
seed_database = true

[debug.databases.postgresql_database]
url = "postgresql://zauth:zauth@localhost/zauth"

[release]
address = "0.0.0.0"
port = 8000
# Values you want to fill in for production use
# admin_email = # Email address to send admin notifications to (e.g. admin@zeus.gent)
# secret_key =  # used to encrypt cookies (generate a new one!)
# ec_private_key = # Path to ECDSA private key for signing jwt's. Key Algo needs to be ES384 in PKCS#8 form.
#   generate by running: openssl ecparam -genkey -noout -name secp384r1 | openssl pkcs8 -topk8 -nocrypt -out ec-private.pem)
# base_url =    # URL where the application is hosten (e.g. https://auth.zeus.gent)
# mail_from =   # From header to set when sending emails (e.g. zauth@zeus.gent)
# mail_server = # domain of the SMTP server used to send mail (e.g. smtp.zeus.gent)

# See src/config.rs for all the possible config values and their defaults

[release.databases.postgresql_database]
url = "postgresql://zauth:zauth@database/zauth"
