CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(127) NOT NULL,
    password VARCHAR(127) NOT NULL,
    admin    BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE client (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(127) NOT NULL,
    secret VARCHAR(127) NOT NULL,
    needs_grant BOOLEAN NOT NULL DEFAULT 0,
    redirect_uri_list VARCHAR(127) NOT NULL DEFAULT ""
);
