name: Rust

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "zauth_test"
          MYSQL_USER: "zauth"
          MYSQL_PASSWORD: "zauth"
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_HOST: "localhost"
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install system dependencies
      run: sudo apt install libsqlite3-dev libmysqlclient-dev
    - name: Build Zauth
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
    - name: Check formatting
      run: cargo fmt -- --check
