name: Rust

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "zauth_test"
          POSTGRES_USER: "zauth"
          POSTGRES_PASSWORD: "zauth"
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install system dependencies
      run: sudo apt install libsqlite3-dev libmysqlclient-dev
    - name: Cache compiled dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - name: Build Zauth
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
    - name: Check formatting
      run: cargo fmt -- --check
