name: Rust

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "zauth_test"
          MYSQL_USER: "zauth"
          MYSQL_PASSWORD: "zauth"
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_HOST: "localhost"
    steps:
    - uses: actions/checkout@v1
    - name: Install system dependencies
      run: sudo apt install libsqlite3-dev libmysqlclient-dev
    - name: Install Rust nightly and diesel-cli
      run: rustup toolchain install nightly &&
        rustup default nightly &&
        cargo install diesel_cli
    - name: Build Zauth
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust nightly and rustfmt
      run: rustup toolchain install nightly &&
        rustup default nightly &&
        rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt -- --check
