name: Rust

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "zauth_test"
          POSTGRES_USER: "zauth"
          POSTGRES_PASSWORD: "zauth"
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
    - name: Install system dependencies
      run: sudo apt install libsqlite3-dev libmysqlclient-dev
    - name: Cache compiled dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
    - name: Build Zauth
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose

  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Check formatting
      run: cargo fmt -- --check

  build-css:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        cache: npm
    - run: npm install
    - run: npm run build
