name: Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse tag
        id: parse_tag
        run: "echo ${{ github.ref }} | sed 's#^refs/tags/#::set-output name=version::#'"
      - name: Create release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          name: ${{ steps.parse_tag.outputs.version }}
          tag: ${{ steps.parse_tag.outputs.version }}
          version: ${{ steps.parse_tag.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the new image
        run: docker build . -t ghcr.io/ZeusWPI/zauth:${{ steps.parse_tag.outputs.version }}
      - name: Login to the container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Tag the new image with latest
        run: docker tag ghcr.io/ZeusWPI/zauth:${{ steps.parse_tag.outputs.version }} ghcr.io/ZeusWPI/zauth:latest
      - name: Push the new image
        run: docker push --all-tags
